services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entry.sh"]
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: practice
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: practice
    ports:
      - "3307:3306"
volumes:
  mysql_data:
